### ISSUE TITLE
Ran the installer, logs are showing clear and I am on the latest release but I cannot get the mods to load in game

### ISSUE THREAD

**Issue by HermanCodes** [MrBacanudo/SkulHardModeMods#1]
[Message:   BepInEx] BepInEx 5.4.21.0 - Skul (6/11/2022 1:06:20 PM)
[Info   :   BepInEx] Running under Unity v2020.3.34.10112156
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 8 plugins to load
[Info   :   BepInEx] Loading [AwakeOnCastle 0.0.1]
[Info   :AwakeOnCastle] Mod AwakeOnCastle is loaded!
[Info   :   BepInEx] Loading [DuplicatesOnCastle 0.0.1]
[Info   :DuplicatesOnCastle] Mod DuplicatesOnCastle is loaded!
[Info   :   BepInEx] Loading [LegendaryStart 0.0.1]
[Info   :LegendaryStart] Mod LegendaryStart is loaded!
[Info   :   BepInEx] Loading [NineItems 0.0.1]
[Info   : NineItems] Mod NineItems is loaded!
[Info   :   BepInEx] Loading [OmenAndSinStart 0.0.1]
[Info   :OmenAndSinStart] Mod OmenAndSinStart is loaded!
[Info   :   BepInEx] Loading [QuintessenceStart 0.0.1]
[Info   :QuintessenceStart] Mod QuintessenceStart is loaded!
[Info   :   BepInEx] Loading [RerollCurses 0.0.1]
[Info   :RerollCurses] Mod RerollCurses is loaded!
[Info   :   BepInEx] Loading [RerollsOnCastle 0.0.1]
[Info   :RerollsOnCastle] Mod RerollsOnCastle is loaded!
[Message:   BepInEx] Chainloader startup complete

So above is the BepInEx logs, I am on the latest release of the game and it all works, but when I go into the game the items as shown in your video are no where to be seen in the dark mirror.

Any ideas?

**Comment by MrBacanudo** [comment]
What level of the Dark Mirror are you on?

If you haven't beaten Level 0, you won't see any machines, and this mod uses the machines that you've already unlocked.
