### ISSUE TITLE
Is there any way, via mod, to show you 'post-stat' cooldown timers?

### ISSUE THREAD

**Issue by RandomNerd1** [MrBacanudo/SkulHardModeMods#10]
For example, you have a skill with cooldown of 10 seconds, and you have 100% cooldown speed reduction. When you're looking at the screen where it would show you the 10, if it could have next to it a "5.00" (two decimal places would be good for calculations less clean than this example), which is what the cooldown actually is, would be great.

Similar request for quintessence cooldowns. :)

**Comment by MrBacanudo** [comment]
That's a cool idea! Right now, I'm not working on any mods. But when I do, I'll ensure to try this one out. It's definitely possible!

**Comment by MrBacanudo** [comment]
Mod published! `DisplayRealCooldowns` is now available on the releases tab, and on the Thunderstore. Thank you for your suggestion!
