### ISSUE TITLE
cannot extract files

### ISSUE THREAD

**Issue by hzuilquigmnzhah** [MrBacanudo/SkulHardModeMods#4]
i download the installer and white list it on all of my antivirus but then when i open it it says the files could not be extracted please help

**Comment by MrBacanudo** [comment]
That's an interesting one... Are you able to manually create files in the Skul game folder?

One easy way to try it out would be running as administrator. But it's the first time I see anything like this happening, at all!

**Comment by hzuilquigmnzhah** [comment]
tried running it as admin and yes i can create a new folder in the skul game folder 
same issue as before, i downloaded it and have the application installer, i try to run the installer and at just says files cannot be extracted

**Comment by hzuilquigmnzhah** [comment]
heres a screenshot if it helps any 

![image_2023-03-01_182540317](https://user-images.githubusercontent.com/126609663/222229701-c82312a8-16cc-4dc7-8a31-303add3ce64d.png)

**Comment by MrBacanudo** [comment]
Are all files downloaded on the `.downloads` folder?

**Comment by hzuilquigmnzhah** [comment]
just tried putting the skulmoddownloader into the .downloads folder still doing it, would it maybe help if i tried redownloading the mod do you think?

**Comment by hzuilquigmnzhah** [comment]
just tried to redownload it but no luck

**Comment by MrBacanudo** [comment]
Putting the file there won't change anything.
I just wanted to know if the downloader actually downloaded all files. Can you attach a screenshot of that folder's content? 

It should have 4 zip files in it:

![image](https://user-images.githubusercontent.com/73220344/222292030-17b0be5d-425a-415e-a083-603b6254b581.png)

**Comment by hzuilquigmnzhah** [comment]
![image_2023-03-01_234230725](https://user-images.githubusercontent.com/126609663/222292216-1df34643-459c-42f4-85c5-f174e7da198a.png)

**Comment by hzuilquigmnzhah** [comment]
....did i accidentally already manage it without realising?

**Comment by MrBacanudo** [comment]
This only confirms the download completed, so the error message is on the correct spot.
Now, why is it not able to extract those zips? I have no idea.

Could you try the manual installation method, using those zips? Wherever it's failing, it should also fail by trying manually.

Also, did you try running as administrator? If it's a "can't create a folder here" issue, it would work.

**Comment by hzuilquigmnzhah** [comment]
am having trouble finding the root folder for skul, im in the skul folder but cant see winhttp.dll or doorstop_config.ini not sure if its just something wrong with me or something 
![image_2023-03-02_003504033](https://user-images.githubusercontent.com/126609663/222299477-f3166c05-5e88-4ac7-84e6-1ff809bdd496.png)

this is all i see ive been looking through them for those files it specifies in the instructions but cant find them, im not sure if im just missing them or what

**Comment by MrBacanudo** [comment]
For the manual installation, you need to first extract those files from their respective zips.

**Comment by hzuilquigmnzhah** [comment]
i did i put them into a folder called skul mods so i dont mess up anything, was that not a good idea?

**Comment by MrBacanudo** [comment]
They need to be in the game root, by the executable.

**Comment by hzuilquigmnzhah** [comment]
ok they are all in the root next to the skul executable

**Comment by hzuilquigmnzhah** [comment]
sorry for bugging you so much by the way i am barely computer literate thank you for helping me

**Comment by MrBacanudo** [comment]
No worries!

Were you able to run it now?

**Comment by hzuilquigmnzhah** [comment]
i buggered up and was trying to do stuff with the automatic version i think i have got the correct ones now, i am at the final step that says to download mods, am i just supposed to download them and unzip them into the root folder or into a new one or what?

**Comment by hzuilquigmnzhah** [comment]
because looking at the bepinx folder only shows core

**Comment by MrBacanudo** [comment]
The mods need to be inside the `plugins` folder inside `BepInEx` (create it inside, if it doesn't exist. BepInEx must exist already, though)

**Comment by hzuilquigmnzhah** [comment]
i can see a folder named pluging in another folder, not that one?just want to be sure im not messing up

**Comment by hzuilquigmnzhah** [comment]
inside of skul data to be specific

**Comment by MrBacanudo** [comment]
Like this.

![image](https://user-images.githubusercontent.com/73220344/222305361-619cdf86-4f77-4430-a548-2450a6d3a541.png)

The dlls for each mod must be inside:

![image](https://user-images.githubusercontent.com/73220344/222305426-37acf770-55d1-4ccc-be39-17f2cf0e6b69.png)

**Comment by hzuilquigmnzhah** [comment]
never mind i think its working i just tested it and can see legendaries in the reroll
thank god! that was an ordeal
thank you so much for helping me 
do you have a patreon by chance so i can give you a fiver for helping my autistic self?

**Comment by MrBacanudo** [comment]
Don't worry! Your enjoyment is good enough for me! ❤️ 
I'm closing this one; Have fun!
