### ISSUE TITLE
the files in the manual installation guide do not exist

### ISSUE THREAD

**Issue by 1wingroad** [MrBacanudo/SkulHardModeMods#6]
As the title says the folders and files labeled don't exist could u provide an update about which folders i should use for the steam verion of the game

**Comment by MrBacanudo** [comment]
The description is there for the Steam version of the game.
The files should be extracted from the 3 links on step 1.

1. At the end of installing the mods, your Skul folder should look like 
![this](https://cdn.discordapp.com/attachments/1087338936038346832/1087436490725933176/image.png)
2. The mod files must be inside a `plugins` folder you create inside `BepInEx`, like 
![this](https://cdn.discordapp.com/attachments/1087338936038346832/1087436626696867932/image.png).
3. The folder `2020.3.34` must be created inside the game folder, and both files that had that name must be extracted to that folder, totaling 79 files inside it, without any folder inside, like 
![this](https://cdn.discordapp.com/attachments/1087338936038346832/1087436780300664902/image.png).

**Comment by namcp274** [comment]
I can't find the winhttp.dll and doorstop_config.ini anywhere in my PC?
